[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "toolHandlerJLT"
version = "0.0.4"
authors = [
  { name="Jielong Tang", email="tjl928@163.com" },
]
description = "A small tool package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/tangjielong928/Deep-Learning_FinalProject"
"Bug Tracker" = "https://github.com/tangjielong928/Deep-Learning_FinalProject/issues"