[tool.poetry]
name = "mtb_log"
version = "0.5.0"
description = "Logging utilities"
license = "GPL-3.0-only"
authors = ["Mel Massadian <melmassadian@gmail.com>"]
maintainers = ["Mel Massadian <melmassadian@gmail.com>"]
readme = "README.md"
keywords = ["logging", "logging utilities"]
classifiers= [
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
    ]
packages = [
    { include = "mtb" },
]

[tool.poetry.dependencies]
python = ">=3.6.2 <3.10"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.20.0"

[build-system]
requires = ["poetry==1.0.10"]
build-backend = "poetry.masonry.api"

