[tool.poetry]
name = "ces-mwaa-utils"
version = "0.1.0"
description = "Utilities for working for Managed Workflows for Apache Airflow"
authors = ["Manoj Karthick <manojkarthick@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "1.18.65"
requests = "2.26.0"
PyYAML = "5.4.1"
apache-airflow = "2.2.2"
apache-airflow-providers-slack = "4.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
airflow-utils = "ces_mwaa_utils.cli:run"
