[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "progb"
version = "0.0.6"
authors = [
  { name="Henry Cook", email="henryscookolaizola@gmail.com" },
]
description = "A simple Python package to display progress bars on all operating systems"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/HCook86/progb"
"Bug Tracker" = "https://github.com/HCook86/progb"

