[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "rpgmaincore"
version = "0.0.6b"
authors = [
  { name="lopotichaaaa", email="riioze0@gmail.com" },
]
description = "a library to create rpg"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/riioze/rpgmaincore"
"Bug Tracker" = "https://github.com/riioze/rpgmaincore/issues"
