[build-system]
requires =["hatchling"]
build-backend = "hatchling.build"


[project]
dependencies =["Pillow >= 8.4.0", "matplotlib >= 3.0.0"]

name ="ormedian_resizer"
version = "0.0.1.4"
authors = [{name = "Samuel Adebayo", email = "samuel@ormedian.com"}]
license = {file ="LICENSE"}
requires-python = ">=3.6"
classifiers = [
    "License :: OSI Approved :: MIT License",
"Programming Language :: Python",
"Programming Language :: Python :: 3"]

keywords = ["image resizer", "reduce size", "reduce image quality", "image", "jpg", "png"]

[project.urls]
"Homepage" = "https://github.com/exponentialR/ormedian-resizer"




#[project.scripts]
#ormedian-ormedian_resizer = "ormedian_resizer.__main__:main"
