[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "uaromanizer"
version = "0.0.2"
authors = [
  { name="Mars Maps", email="m4rsm4ps@gmail.com" },
]
description = "Romanization of Ukrainian writing"
readme = "README.md"
license = { file="LICENSE" }
keywords = ['Ukrainian', 'romanization']
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/m4rsm4ps/uaromanizer"
"Bug Tracker" = "https://github.com/m4rsm4ps/uaromanizer/issues"