[tool.poetry]
name = "wallstreet_judge"
version = "0.5.0"
description = ""
authors = ["Kushal Chordiya <kushal.chordiya@trilogy.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
typer = "^0.6.1"
pydantic = "^1.9.1"
colorama = "^0.4.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wallstreet_judge = "wallstreet_judge.main:app"