[tool.poetry]
name = "data_job_crawler"
version = "0.2.0"
description = ""
authors = ["Donor <donorfelita@msn.com>"]

[tool.poetry.dependencies]
python = "^3.9"
psycopg2 = "^2.9.3"
Scrapy = "^2.6.2"
playwright = "^1.24.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
