[tool.poetry]
name = "data-job-etl"
version = "0.5.0"
description = ""
authors = ["Donor <donorfelita@msn.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.3"
SQLAlchemy = "^1.4.39"
psycopg2 = "^2.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
