[tool.poetry]
name = "animal-language"
version = "0.1.1"
description = "Customize a word set, and then use the words in this set to represent any sentence."
authors = ["chnzzh <chnzzh@outlook.com>"]
readme = "README.md"
repository = "https://github.com/chnzzh/animal-language"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/chnzzh/animal-language/issues"