
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "scdbf"
version = "0.0.3"
description = "Simple cat for dbf files"
authors = [
  { name="Jesus Baizabal", email="baizabal.jesus@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.5"
keywords = ["cat", "dbf"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "dbfread",
]
[project.urls]
"Homepage" = "https://github.com/ambagasdowa/scdbf"
"Bug Tracker" = "https://github.com/ambagasdowa/scdbf/issues"
[project.scripts]
cli-name = "scdbf.scdbf:main"

#dynamic = ["version"]

#[project.optional-dependencies]
#pdf = ["ReportLab>=1.2", "RXP"]
#rest = ["docutils>=0.3", "pack ==1.1, ==1.3"]
#
#[project.scripts]
#my-script = "my_package.module:function"

# ... other project metadata fields as specified in:
#     https://packaging.python.org/en/latest/specifications/declaring-project-metadata/


