[tool.poetry]
name = "testcontainer-python-minio"
version = "0.4.0"
description = ""
authors = ["Max Fr√∂hlich <max.froehlich@serviceware.de>"]

[tool.poetry.dependencies]
python = "^3.8"
testcontainers = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^5.0.3"
black = "^22.6.0"
boto3 = "^1.24.44"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
