[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "oru2xds"
# version="2.0.1"
dynamic = ["version"]
authors = [
    { name="Antonio Martins", email="digiplan.pt@gmail.com" },
]
description = "Receive HL7 messages and send them to an XDS.b repository"
readme = "README.md"
license = { file = "LICENSE.md" }
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
	"aiorun==2022.4.1",
	"hl7==0.4.5",
	"lxml==4.8.0",
	"requests==2.25.1",
	"requests_toolbelt==0.9.1",
	"striprtf==0.0.20",
	"sympy==1.10.1",
	"urllib3==1.26.5",
]

[tool.setuptools.dynamic]
version = {attr = "oru2xds/__version__.__version__"}
