[tool.poetry]
name = "bagbag"
version = "0.27.3"
description = "An all in one python library"

license = "MIT"

authors = [
    "Darren"
]

readme = 'README.md'

repository = "https://github.com/darren2046/bagbag"

keywords = ['base', 'library']

exclude = [
  ".git",
  "ident",
  "publish.py",
  "__pycache__",
  ".github",
  "*.ident",
]

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.6.0"
redis = "^4.3.4"
orator = "^0.9.9"
PyMySQL = "^1.0.2"
telethon = "^1.24.0"
langid = "^1.1.6"
selenium = "^4.3.0"
Flask = "^2.1.3"
tqdm = "^4.64.0"
prometheus-client = "^0.14.1"
ipdb = "^0.13.9"
requests = "^2.28.1"
requests-toolbelt = "^0.9.1"
pyTelegramBotAPI = "^4.6.1"
Pillow = "^9.2.0"

[build-system]
requires = ["poetry>=0.12a3"]
build-backend = "poetry.masonry.api"