[project]
name="rf_otp"
version = "0.1.11"
description = "RobotFramework tools provided by QA team"
authors = [
    {name = "Pedro Lopez Perez", email = "pedro.lopez-perez@etat.ge.ch"},
]
dependencies = [
    "pyotp==2.6.0"
    ]

requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[tool.pip]

[build-system]
requires = ["setuptools>=62.3.2",
            "build>=0.8.0"]
build-backend = "setuptools.build_meta"